name: mooknote
description: "app for tracking movies, books, and notes"
publish_to: 'none'
version: 0.2.7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.69.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_markdown_plus: ^1.0.7
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  cross_file: ^0.3.4
  archive: ^3.6.0
  xml: ^6.6.1
  permission_handler: ^11.3.0
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  flutter_inappwebview: ^6.1.5
  dynamic_color: ^1.8.1
  package_info_plus: ^8.0.0
  uuid: ^4.5.0
  expandable: ^5.0.1
  sqflite_common_ffi: ^2.3.0
  device_info_plus: ^11.2.0
  crypto: ^3.0.6
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/app_icon.webp"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.webp"
  min_sdk_android: 21

hooks:
  user_defines:
    sqlite3:
      source: system

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/images/ticket/
    - assets/images/imp_book/
    - assets/vditor/
    - assets/vditor/dist/
    - assets/vditor/dist/css/
    - assets/vditor/dist/css/content-theme/
    - assets/vditor/dist/images/
    - assets/vditor/dist/images/emoji/
    - assets/vditor/dist/js/abcjs/
    - assets/vditor/dist/js/echarts/
    - assets/vditor/dist/js/flowchart.js/
    - assets/vditor/dist/js/graphviz/
    - assets/vditor/dist/js/highlight.js/
    - assets/vditor/dist/js/highlight.js/styles/
    - assets/vditor/dist/js/i18n/
    - assets/vditor/dist/js/icons/
    - assets/vditor/dist/js/katex/
    - assets/vditor/dist/js/katex/fonts/
    - assets/vditor/dist/js/lute/
    - assets/vditor/dist/js/markmap/
    - assets/vditor/dist/js/mathjax/
    - assets/vditor/dist/js/mathjax/a11y/
    - assets/vditor/dist/js/mathjax/input/
    - assets/vditor/dist/js/mathjax/input/mml/
    - assets/vditor/dist/js/mathjax/input/tex/
    - assets/vditor/dist/js/mathjax/input/tex/extensions/
    - assets/vditor/dist/js/mathjax/sre/
    - assets/vditor/dist/js/mathjax/sre/mathmaps/
    - assets/vditor/dist/js/mermaid/
    - assets/vditor/dist/js/plantuml/
    - assets/vditor/dist/js/smiles-drawer/
